[workspace]
resolver = "2"
members = [
    "metrics",
    "sn_build_info",
    "sn_faucet",
    "sn_logging",
    "sn_networking",
    "sn_peers_acquisition",
    "sn_protocol",
    "sn_registers",
    "sn_transfers",
]
