[package]
name = "ant_rewards_service"
version = "0.1.0"
edition = "2021"

[dependencies]
autonomi = { git = "https://github.com/mickvandijke/autonomi", rev = "e2d83bb5252e2e675f935e34bec64b4a2fcbed70" }
clap = "4.5.28"
eyre = "0.6.12"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
xor_name = "5.0.0"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
hex = "0.4.3"
