[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Protocol"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_protocol"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.8.31"

[features]
test-utils=["dirs-next", "serde_json"]

[dependencies]
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
color-eyre = "0.6.2"
crdts = { version = "7.3", default-features = false, features = ["merkle"] }
custom_debug = "~0.5.0"
dirs-next = { version = "~2.0.0", optional = true }
hex = "~0.4.3"
libp2p = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["identify", "kad"] }
rmp-serde = "1.1.1"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
serde_json = {version = "1.0", optional = true }
sha2 = "0.10.7"
sn_transfers = { path = "../sn_transfers", version = "0.14.21" }
sn_registers = { path = "../sn_registers", version = "0.3.3" }
thiserror = "1.0.23"
tracing = { version = "~0.1.26" }
# # watch out updating this, protoc compiler needs to be installed on all build systems
# # arm builds + musl are very problematic
prost = { version = "0.9" }
tonic = { version = "0.6.2" }
xor_name = "5.0.0"

[build-dependencies]
# watch out updating this, protoc compiler needs to be installed on all build systems
# arm builds + musl are very problematic
tonic-build = { version = "~0.6.2" }
