[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Node RPC Client"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node_rpc_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.46"

[[bin]]
path="src/main.rs"
name="safenode_rpc_client"

[dependencies]
assert_fs = "1.0.0"
async-trait = "0.1"
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "0.6.2"
hex = "~0.4.3"
libp2p = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["kad"]}
libp2p-identity = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["rand", "peerid"] }
sn_client = { path = "../sn_client", version = "0.98.18" }
sn_logging = { path = "../sn_logging", version = "0.2.15" }
sn_node = { path = "../sn_node", version = "0.98.36" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.1.10" }
sn_protocol = { path = "../sn_protocol", version = "0.8.31" }
sn_transfers = { path = "../sn_transfers", version = "0.14.21" }
thiserror = "1.0.23"
# # watch out updating this, protoc compiler needs to be installed on all build systems
# # arm builds + musl are very problematic
tonic = { version = "0.6.2" }
tokio = { version = "1.32.0", features = ["parking_lot", "rt"] }
tokio-stream = { version = "~0.1.12" }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"
