[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network CLI"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_cli"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.86.25"

[[bin]]
path="src/main.rs"
name="safe"

[[bench]]
name = "files"
harness = false

[features]
default = ["metrics"]
local-discovery=["sn_client/local-discovery", "sn_peers_acquisition/local-discovery"]
metrics = ["sn_logging/process-metrics"]
network-contacts = ["sn_peers_acquisition/network-contacts"]
open-metrics = ["sn_client/open-metrics"]

[dependencies]
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
custom_debug = "~0.5.0"
chrono = "~0.4.19"
clap = { version = "4.2.1", features = ["derive"]}
color-eyre = "~0.6"
dirs-next = "~2.0.0"
hex = "~0.4.3"
indicatif = { version = "0.17.5", features = ["tokio"] }
libp2p = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["identify", "kad"] }
rayon = "1.8.0"
reqwest = { version="0.11.18", default-features=false, features = ["rustls"] }
sn_build_info = { path="../sn_build_info", version = "0.1.2" }
sn_client = { path = "../sn_client", version = "0.98.18" }
sn_transfers = { path = "../sn_transfers", version = "0.14.21" }
sn_logging = { path = "../sn_logging", version = "0.2.15" }
sn_peers_acquisition= { path="../sn_peers_acquisition", version = "0.1.10" }
sn_protocol = { path = "../sn_protocol", version = "0.8.31" }
tempfile = "3.6.0"
tokio = { version = "1.32.0", features = ["io-util", "macros", "parking_lot", "rt", "sync", "time", "fs"] }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"
url = "2.4.0"
walkdir = "~2.4.0"
xor_name = "5.0.0"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.6.0"
rand = { version = "~0.8.5", features = ["small_rng"] }
sn_protocol = { path = "../sn_protocol", version = "0.8.31", features = ["test-utils"]}
