[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Networking Infrastructure"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_networking"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.10.22"

[features]
default=[]
local-discovery=["libp2p/mdns"]
quic=["libp2p/quic"]
open-metrics=["libp2p/metrics", "prometheus-client", "hyper", "sysinfo"]

[dependencies]
async-trait = "0.1"
bytes = { version = "1.0.1", features = ["serde"] }
futures = "~0.3.13"
hyper = { version = "0.14", features = ["server", "tcp", "http1"], optional = true}
itertools = "~0.11.0"
custom_debug = "~0.5.0"
libp2p = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["tokio", "dns", "kad", "macros", "request-response", "cbor","identify", "autonat", "noise", "tcp", "yamux", "gossipsub"] }
prometheus-client = { version = "0.22", optional = true }
rand = { version = "~0.8.5", features = ["small_rng"] }
rayon = "1.8.0"
rmp-serde = "1.1.1"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
sn_protocol = { path = "../sn_protocol", version = "0.8.31" }
sn_transfers = { path = "../sn_transfers", version = "0.14.21" }
sysinfo = { version = "0.29.0", default-features = false, optional = true }
thiserror = "1.0.23"
tiny-keccak = { version = "~2.0.2", features = [ "sha3" ] }
tokio = { version = "1.32.0", features = ["io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tracing = { version = "~0.1.26" }
xor_name = "5.0.0"

[dev-dependencies]
bls = { package = "blsttc", version = "8.0.1" }
# add rand to libp2p
libp2p-identity = { git = "https://github.com/maqi/rust-libp2p", branch = "two_fixes_combined", features = ["rand"] }
quickcheck = "1.0.3"
eyre = "0.6.8"
